#!/usr/bin/env python3
"""Generate the checked third-party dependency notice inventory.

The generated document is intentionally an inventory and review aid, not a
replacement for final human legal review. It is kept in source control so CI can
fail when version-catalog or Rust manifest dependencies change without a notice
reconciliation.
"""

from __future__ import annotations

import argparse
import difflib
import sys
import tomllib
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
NOTICE_PATH = ROOT / "docs" / "THIRD_PARTY_NOTICES.md"
ANDROID_CATALOG = ROOT / "gradle" / "libs.versions.toml"
RUST_MANIFESTS = [
    ROOT / "core" / "Cargo.toml",
    ROOT / "tools" / "uniffi-bindgen" / "Cargo.toml",
]


def load_toml(path: Path) -> dict[str, Any]:
    with path.open("rb") as handle:
        return tomllib.load(handle)


def version_from_catalog(spec: Any, versions: dict[str, Any]) -> str:
    if isinstance(spec, str):
        return spec
    if not isinstance(spec, dict):
        return "unversioned"
    direct_version = spec.get("version")
    if isinstance(direct_version, str):
        return direct_version
    if isinstance(direct_version, dict):
        ref = direct_version.get("ref")
        if isinstance(ref, str):
            return str(versions[ref])
    dotted_ref = spec.get("version.ref")
    if isinstance(dotted_ref, str):
        return str(versions[dotted_ref])
    return "managed by platform/BOM"


def rust_version(spec: Any) -> str:
    if isinstance(spec, str):
        return spec
    if isinstance(spec, dict) and isinstance(spec.get("version"), str):
        return spec["version"]
    return "workspace/path/local"


def generate() -> str:
    catalog = load_toml(ANDROID_CATALOG)
    versions = catalog.get("versions", {})
    libraries = catalog.get("libraries", {})
    plugins = catalog.get("plugins", {})

    lines: list[str] = [
        "# Third-party dependency notices",
        "",
        "This file is generated by `scripts/generate_third_party_notices.py`.",
        "It is a dependency inventory for engineering, release, and legal review; it does not itself approve any dependency license for release.",
        "",
        "## Android and JVM libraries from `gradle/libs.versions.toml`",
        "",
        "| Alias | Module | Version |",
        "| --- | --- | --- |",
    ]

    for alias in sorted(libraries):
        spec = libraries[alias]
        module = spec.get("module", alias) if isinstance(spec, dict) else alias
        lines.append(f"| `{alias}` | `{module}` | `{version_from_catalog(spec, versions)}` |")

    lines.extend([
        "",
        "## Gradle plugins from `gradle/libs.versions.toml`",
        "",
        "| Alias | Plugin id | Version |",
        "| --- | --- | --- |",
    ])

    for alias in sorted(plugins):
        spec = plugins[alias]
        plugin_id = spec.get("id", alias) if isinstance(spec, dict) else alias
        lines.append(f"| `{alias}` | `{plugin_id}` | `{version_from_catalog(spec, versions)}` |")

    lines.extend([
        "",
        "## Rust crate manifests",
        "",
        "| Manifest | Scope | Crate | Version |",
        "| --- | --- | --- | --- |",
    ])

    for manifest in RUST_MANIFESTS:
        data = load_toml(manifest)
        rel = manifest.relative_to(ROOT).as_posix()
        for scope in ("dependencies", "dev-dependencies", "build-dependencies"):
            deps = data.get(scope, {})
            for name in sorted(deps):
                lines.append(f"| `{rel}` | `{scope}` | `{name}` | `{rust_version(deps[name])}` |")

    lines.extend([
        "",
        "## Review policy",
        "",
        "Dependency additions or version changes must keep this file reconciled and must pass the supply-chain workflow. Advisory or license exceptions must be documented in `docs/SUPPLY_CHAIN_POLICY.md` before release qualification.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked notice file is stale")
    args = parser.parse_args()

    generated = generate()
    if args.check:
        current = NOTICE_PATH.read_text(encoding="utf-8") if NOTICE_PATH.exists() else ""
        if current != generated:
            diff = difflib.unified_diff(
                current.splitlines(),
                generated.splitlines(),
                fromfile=str(NOTICE_PATH),
                tofile="generated",
                lineterm="",
            )
            print("\n".join(diff), file=sys.stderr)
            return 1
        return 0

    NOTICE_PATH.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
